/**
 * Localized UI strings for blog article pages
 * Used by the shared BlogArticleContent component
 */

export interface BlogStrings {
  quickAnswer: string;
  inThisArticle: string;
  conclusion: string;
  faqs: string;
  needHelp: string;
  personalRecs: string;
  bookVideoCall: string;
  exploreProperties: string;
  browseDevelopments: string;
  exploreAreas: string;
  golfProperties: string;
  latestPrices: string;
  pricesChangeDesc: string;
  requestPriceList: string;
  continueReading: string;
  moreGuides: string;
  readyToFind: string;
  readyToFindDesc: string;
  freeConsultation: string;
  viewDevelopments: string;
  minRead: string;
  exploreTheseAreas: string;
  updated: string;
  consultation: string;
  consultationDesc: string;
}

const strings: Record<string, BlogStrings> = {
  en: {
    quickAnswer: 'Quick Answer',
    inThisArticle: 'In This Article',
    conclusion: 'The Bottom Line',
    faqs: 'Frequently Asked Questions',
    needHelp: 'Need Expert Help?',
    personalRecs: 'Get personalized property recommendations from our Costa Blanca specialists.',
    bookVideoCall: 'Book Video Call',
    exploreProperties: 'Explore Properties',
    browseDevelopments: 'Browse Developments',
    exploreAreas: 'Explore Areas',
    golfProperties: 'Golf Properties',
    latestPrices: 'Get Latest Prices',
    pricesChangeDesc: 'Prices change frequently. Get today\'s prices and availability direct from developers.',
    requestPriceList: 'Request Price List',
    continueReading: 'Continue Reading',
    moreGuides: 'More guides to help you buy property in Spain',
    readyToFind: 'Ready to Find Your New Build Home?',
    readyToFindDesc: 'Book a free consultation with our property experts. We\'ll help you find the perfect property in Costa Blanca.',
    freeConsultation: 'Book Free Consultation',
    viewDevelopments: 'Browse Developments',
    minRead: 'min read',
    exploreTheseAreas: 'Explore These Areas',
    updated: 'Updated',
    consultation: 'Free Investment Consultation',
    consultationDesc: 'Speak with our property specialists about your investment goals. We\'ll help you find the right property.',
  },
  nl: {
    quickAnswer: 'Snel antwoord',
    inThisArticle: 'In dit artikel',
    conclusion: 'Conclusie',
    faqs: 'Veelgestelde vragen',
    needHelp: 'Hulp nodig?',
    personalRecs: 'Persoonlijke aanbevelingen van onze Costa Blanca specialisten.',
    bookVideoCall: 'Boek videogesprek',
    exploreProperties: 'Ontdek woningen',
    browseDevelopments: 'Bekijk projecten',
    exploreAreas: 'Ontdek gebieden',
    golfProperties: 'Golfwoningen',
    latestPrices: 'Actuele prijzen',
    pricesChangeDesc: 'Prijzen veranderen regelmatig. Vraag de laatste prijzen en beschikbaarheid aan.',
    requestPriceList: 'Prijslijst aanvragen',
    continueReading: 'Lees verder',
    moreGuides: 'Meer gidsen over vastgoed kopen in Spanje',
    readyToFind: 'Klaar om uw droomhuis te vinden?',
    readyToFindDesc: 'Boek een gratis adviesgesprek met onze vastgoedexperts. Wij helpen u de perfecte woning te vinden.',
    freeConsultation: 'Gratis adviesgesprek',
    viewDevelopments: 'Bekijk projecten',
    minRead: 'min leestijd',
    exploreTheseAreas: 'Ontdek deze gebieden',
    updated: 'Bijgewerkt',
    consultation: 'Gratis investeringsconsultatie',
    consultationDesc: 'Spreek met onze vastgoedspecialisten over uw investeringsdoelen. Wij helpen u de juiste woning te vinden.',
  },
  'nl-be': {
    quickAnswer: 'Snel antwoord',
    inThisArticle: 'In dit artikel',
    conclusion: 'Conclusie',
    faqs: 'Veelgestelde vragen',
    needHelp: 'Hulp nodig?',
    personalRecs: 'Persoonlijke aanbevelingen van onze Costa Blanca specialisten.',
    bookVideoCall: 'Boek videogesprek',
    exploreProperties: 'Ontdek woningen',
    browseDevelopments: 'Bekijk projecten',
    exploreAreas: 'Ontdek gebieden',
    golfProperties: 'Golfwoningen',
    latestPrices: 'Actuele prijzen',
    pricesChangeDesc: 'Prijzen veranderen regelmatig. Vraag de laatste prijzen en beschikbaarheid aan.',
    requestPriceList: 'Prijslijst aanvragen',
    continueReading: 'Lees verder',
    moreGuides: 'Meer gidsen over vastgoed kopen in Spanje',
    readyToFind: 'Klaar om uw droomhuis te vinden?',
    readyToFindDesc: 'Boek een gratis adviesgesprek met onze vastgoedexperts. Wij helpen u de perfecte woning te vinden.',
    freeConsultation: 'Gratis adviesgesprek',
    viewDevelopments: 'Bekijk projecten',
    minRead: 'min leestijd',
    exploreTheseAreas: 'Ontdek deze gebieden',
    updated: 'Bijgewerkt',
    consultation: 'Gratis investeringsconsultatie',
    consultationDesc: 'Spreek met onze vastgoedspecialisten over uw investeringsdoelen. Wij helpen u de juiste woning te vinden.',
  },
  sv: {
    quickAnswer: 'Snabbt svar',
    inThisArticle: 'I denna artikel',
    conclusion: 'Sammanfattning',
    faqs: 'Vanliga frågor',
    needHelp: 'Behöver du hjälp?',
    personalRecs: 'Få personliga fastighetsrekommendationer från våra Costa Blanca-specialister.',
    bookVideoCall: 'Boka videosamtal',
    exploreProperties: 'Utforska fastigheter',
    browseDevelopments: 'Bläddra projekt',
    exploreAreas: 'Utforska områden',
    golfProperties: 'Golffastigheter',
    latestPrices: 'Senaste priserna',
    pricesChangeDesc: 'Priserna ändras ofta. Få dagens priser och tillgänglighet direkt från byggherrar.',
    requestPriceList: 'Begär prislista',
    continueReading: 'Fortsätt läsa',
    moreGuides: 'Fler guider om att köpa bostad i Spanien',
    readyToFind: 'Redo att hitta ditt drömhus?',
    readyToFindDesc: 'Boka en kostnadsfri konsultation med våra fastighetsexperter.',
    freeConsultation: 'Boka gratis konsultation',
    viewDevelopments: 'Bläddra projekt',
    minRead: 'min läsning',
    exploreTheseAreas: 'Utforska dessa områden',
    updated: 'Uppdaterad',
    consultation: 'Gratis investeringskonsultation',
    consultationDesc: 'Prata med våra fastighetsspecialister om dina investeringsmål.',
  },
  de: {
    quickAnswer: 'Schnelle Antwort',
    inThisArticle: 'In diesem Artikel',
    conclusion: 'Fazit',
    faqs: 'Häufig gestellte Fragen',
    needHelp: 'Hilfe benötigt?',
    personalRecs: 'Persönliche Immobilienempfehlungen von unseren Costa Blanca Spezialisten.',
    bookVideoCall: 'Videoanruf buchen',
    exploreProperties: 'Immobilien entdecken',
    browseDevelopments: 'Projekte ansehen',
    exploreAreas: 'Gebiete entdecken',
    golfProperties: 'Golf-Immobilien',
    latestPrices: 'Aktuelle Preise',
    pricesChangeDesc: 'Preise ändern sich häufig. Aktuelle Preise und Verfügbarkeit direkt vom Bauträger.',
    requestPriceList: 'Preisliste anfordern',
    continueReading: 'Weiterlesen',
    moreGuides: 'Weitere Ratgeber zum Immobilienkauf in Spanien',
    readyToFind: 'Bereit, Ihr Traumhaus zu finden?',
    readyToFindDesc: 'Buchen Sie eine kostenlose Beratung mit unseren Immobilienexperten.',
    freeConsultation: 'Kostenlose Beratung',
    viewDevelopments: 'Projekte ansehen',
    minRead: 'Min. Lesezeit',
    exploreTheseAreas: 'Entdecken Sie diese Gebiete',
    updated: 'Aktualisiert',
    consultation: 'Kostenlose Investitionsberatung',
    consultationDesc: 'Sprechen Sie mit unseren Immobilienspezialisten über Ihre Investitionsziele.',
  },
  fr: {
    quickAnswer: 'Réponse rapide',
    inThisArticle: 'Dans cet article',
    conclusion: 'Conclusion',
    faqs: 'Questions fréquentes',
    needHelp: 'Besoin d\'aide ?',
    personalRecs: 'Recommandations personnalisées de nos spécialistes Costa Blanca.',
    bookVideoCall: 'Réserver un appel vidéo',
    exploreProperties: 'Explorer les biens',
    browseDevelopments: 'Voir les projets',
    exploreAreas: 'Découvrir les zones',
    golfProperties: 'Propriétés golf',
    latestPrices: 'Prix actuels',
    pricesChangeDesc: 'Les prix changent régulièrement. Obtenez les prix et disponibilités du jour.',
    requestPriceList: 'Demander la liste des prix',
    continueReading: 'Continuer la lecture',
    moreGuides: 'Plus de guides pour acheter en Espagne',
    readyToFind: 'Prêt à trouver votre maison de rêve ?',
    readyToFindDesc: 'Réservez une consultation gratuite avec nos experts immobiliers.',
    freeConsultation: 'Consultation gratuite',
    viewDevelopments: 'Voir les projets',
    minRead: 'min de lecture',
    exploreTheseAreas: 'Découvrir ces zones',
    updated: 'Mis à jour',
    consultation: 'Consultation investissement gratuite',
    consultationDesc: 'Parlez avec nos spécialistes immobiliers de vos objectifs d\'investissement.',
  },
  no: {
    quickAnswer: 'Raskt svar',
    inThisArticle: 'I denne artikkelen',
    conclusion: 'Oppsummering',
    faqs: 'Vanlige spørsmål',
    needHelp: 'Trenger du hjelp?',
    personalRecs: 'Få personlige eiendomsanbefalinger fra våre Costa Blanca-spesialister.',
    bookVideoCall: 'Book videosamtale',
    exploreProperties: 'Utforsk eiendommer',
    browseDevelopments: 'Se prosjekter',
    exploreAreas: 'Utforsk områder',
    golfProperties: 'Golfeiendommer',
    latestPrices: 'Siste priser',
    pricesChangeDesc: 'Prisene endres ofte. Få dagens priser og tilgjengelighet direkte fra utbyggere.',
    requestPriceList: 'Be om prisliste',
    continueReading: 'Les videre',
    moreGuides: 'Flere guider om å kjøpe eiendom i Spania',
    readyToFind: 'Klar til å finne drømmeboligen?',
    readyToFindDesc: 'Book en gratis konsultasjon med våre eiendomseksperter.',
    freeConsultation: 'Gratis konsultasjon',
    viewDevelopments: 'Se prosjekter',
    minRead: 'min lesning',
    exploreTheseAreas: 'Utforsk disse områdene',
    updated: 'Oppdatert',
    consultation: 'Gratis investeringskonsultasjon',
    consultationDesc: 'Snakk med våre eiendomsspesialister om dine investeringsmål.',
  },
  pl: {
    quickAnswer: 'Szybka odpowiedź',
    inThisArticle: 'W tym artykule',
    conclusion: 'Podsumowanie',
    faqs: 'Często zadawane pytania',
    needHelp: 'Potrzebujesz pomocy?',
    personalRecs: 'Spersonalizowane rekomendacje od naszych specjalistów Costa Blanca.',
    bookVideoCall: 'Umów wideorozmowę',
    exploreProperties: 'Odkryj nieruchomości',
    browseDevelopments: 'Przeglądaj inwestycje',
    exploreAreas: 'Odkryj regiony',
    golfProperties: 'Nieruchomości golfowe',
    latestPrices: 'Aktualne ceny',
    pricesChangeDesc: 'Ceny zmieniają się często. Uzyskaj aktualne ceny i dostępność od deweloperów.',
    requestPriceList: 'Poproś o cennik',
    continueReading: 'Czytaj dalej',
    moreGuides: 'Więcej poradników o kupnie nieruchomości w Hiszpanii',
    readyToFind: 'Gotowy znaleźć swój wymarzony dom?',
    readyToFindDesc: 'Zarezerwuj bezpłatną konsultację z naszymi ekspertami.',
    freeConsultation: 'Bezpłatna konsultacja',
    viewDevelopments: 'Przeglądaj inwestycje',
    minRead: 'min czytania',
    exploreTheseAreas: 'Odkryj te regiony',
    updated: 'Zaktualizowano',
    consultation: 'Bezpłatna konsultacja inwestycyjna',
    consultationDesc: 'Porozmawiaj z naszymi specjalistami o swoich celach inwestycyjnych.',
  },
  ru: {
    quickAnswer: 'Быстрый ответ',
    inThisArticle: 'В этой статье',
    conclusion: 'Итоги',
    faqs: 'Часто задаваемые вопросы',
    needHelp: 'Нужна помощь?',
    personalRecs: 'Персональные рекомендации от наших специалистов по Коста Бланке.',
    bookVideoCall: 'Записаться на видеозвонок',
    exploreProperties: 'Смотреть недвижимость',
    browseDevelopments: 'Проекты застройки',
    exploreAreas: 'Изучить районы',
    golfProperties: 'Гольф-недвижимость',
    latestPrices: 'Актуальные цены',
    pricesChangeDesc: 'Цены часто меняются. Получите актуальные цены и наличие от застройщиков.',
    requestPriceList: 'Запросить прайс-лист',
    continueReading: 'Читать далее',
    moreGuides: 'Другие руководства по покупке недвижимости в Испании',
    readyToFind: 'Готовы найти дом вашей мечты?',
    readyToFindDesc: 'Запишитесь на бесплатную консультацию с нашими экспертами.',
    freeConsultation: 'Бесплатная консультация',
    viewDevelopments: 'Смотреть проекты',
    minRead: 'мин чтения',
    exploreTheseAreas: 'Изучить эти районы',
    updated: 'Обновлено',
    consultation: 'Бесплатная инвестиционная консультация',
    consultationDesc: 'Поговорите с нашими специалистами о ваших инвестиционных целях.',
  },
};

export function getBlogStrings(lang: string): BlogStrings {
  return strings[lang] || strings.en;
}

// Date locale mapping
const dateLocales: Record<string, string> = {
  en: 'en-GB', nl: 'nl-NL', 'nl-be': 'nl-BE', sv: 'sv-SE',
  de: 'de-DE', fr: 'fr-FR', no: 'nb-NO', pl: 'pl-PL', ru: 'ru-RU',
};

export function getDateLocale(lang: string): string {
  return dateLocales[lang] || 'en-GB';
}
