/**
 * Development Page Utilities
 * ==========================
 * Shared utilities for development pages across all languages.
 * Loads translated development content (JSON) falling back to English.
 */

import fs from 'fs';
import path from 'path';

const CONTENT_DIR = path.join(process.cwd(), 'src', 'content');

/**
 * Development content from flat-format JSON files (generated by AI).
 * These files live in src/content/developments/{lang?}/slug.json
 */
export interface DevelopmentContent {
  metaTitle: string;
  metaDescription: string;
  heroIntro: string;
  areaSection: string;
  lifestyleSection: string;
  locationHighlights: string[];
  propertyFeatures: { intro: string; features: string[] };
  investmentSection: string;
  lifeAndAmenities: {
    intro: string;
    healthcare?: { text: string; keyPoints: string[] };
    education?: { text: string; keyPoints: string[] };
    shopping?: { text: string; keyPoints: string[] };
    transport?: { text: string; keyPoints: string[] };
  };
  whyBuySection: string[];
  priceComparison: { thisProperty?: string; areaAverage?: string; verdict: string };
  buyerPersona: { type: string; perfectFor: string[] };
  faqs: { question: string; answer: string }[];
  imageAlts: string[];
  internalLinks: { area?: string; builder?: string; similarSearch?: string };
  conclusion: string;
  reference: string;
  slug: string;
  source: string;
  town: string;
  generatedAt: string;
}

/**
 * Builder content from JSON files.
 */
export interface BuilderContentData {
  name: string;
  slug: string;
  metaTitle: string;
  metaDescription: string;
  heroHeadline: string;
  heroIntro: string;
  aboutSection: { title: string; content: string };
  specializationSection: { title: string; regions: string[]; towns: string[]; propertyTypes: string[]; content: string };
  qualitySection: { title: string; features: string[]; content: string };
  whyChooseSection: { title: string; reasons: { title: string; description: string }[] };
  faqs: { question: string; answer: string }[];
  conclusion: string;
  stats: any;
  generatedAt: string;
}

/**
 * Load development content for a slug, with language support.
 * Priority: translated version > English version
 */
export function getDevelopmentContent(slug: string, lang?: string): DevelopmentContent | null {
  const devDir = path.join(CONTENT_DIR, 'developments');

  // Try translated version first
  if (lang && lang !== 'en') {
    const langPath = path.join(devDir, lang, `${slug}.json`);
    if (fs.existsSync(langPath)) {
      try {
        const data = JSON.parse(fs.readFileSync(langPath, 'utf-8'));
        if (data.metaTitle && (data.heroIntro || data.content)) return data;
      } catch { /* fall through */ }
    }
  }

  // Fall back to English
  const enPath = path.join(devDir, `${slug}.json`);
  if (fs.existsSync(enPath)) {
    try {
      const data = JSON.parse(fs.readFileSync(enPath, 'utf-8'));
      if (data.metaTitle && (data.heroIntro || data.content)) return data;
    } catch { /* fall through */ }
  }

  return null;
}

/**
 * Load builder content with language support.
 */
export function getBuilderContent(builderSlug: string, lang?: string): BuilderContentData | null {
  const builderDir = path.join(CONTENT_DIR, 'builders');

  // Try translated version
  if (lang && lang !== 'en') {
    const langPath = path.join(builderDir, lang, `${builderSlug}.json`);
    if (fs.existsSync(langPath)) {
      try {
        return JSON.parse(fs.readFileSync(langPath, 'utf-8'));
      } catch { /* fall through */ }
    }
  }

  // English fallback
  const enPath = path.join(builderDir, `${builderSlug}.json`);
  if (fs.existsSync(enPath)) {
    try {
      return JSON.parse(fs.readFileSync(enPath, 'utf-8'));
    } catch { /* fall through */ }
  }

  return null;
}

/**
 * Get all development slugs (for generateStaticParams).
 */
export function getDevelopmentSlugs(lang?: string): string[] {
  const devDir = path.join(CONTENT_DIR, 'developments');
  const slugs: string[] = [];

  // Add from language directory if it exists
  if (lang && lang !== 'en') {
    const langDir = path.join(devDir, lang);
    if (fs.existsSync(langDir)) {
      try {
        const files = fs.readdirSync(langDir).filter(f => f.endsWith('.json'));
        slugs.push(...files.map(f => f.replace('.json', '')));
      } catch {}
    }
  }

  // Add from English directory
  try {
    const files = fs.readdirSync(devDir).filter(f => f.endsWith('.json') && !fs.statSync(path.join(devDir, f)).isDirectory());
    slugs.push(...files.map(f => f.replace('.json', '')));
  } catch {}

  return [...new Set(slugs)];
}

/**
 * Get all builder slugs.
 */
export function getBuilderSlugs(lang?: string): string[] {
  const builderDir = path.join(CONTENT_DIR, 'builders');
  const slugs: string[] = [];

  if (lang && lang !== 'en') {
    const langDir = path.join(builderDir, lang);
    if (fs.existsSync(langDir)) {
      try {
        const files = fs.readdirSync(langDir).filter(f => f.endsWith('.json'));
        slugs.push(...files.map(f => f.replace('.json', '')));
      } catch {}
    }
  }

  try {
    const files = fs.readdirSync(builderDir).filter(f => f.endsWith('.json') && !fs.statSync(path.join(builderDir, f)).isDirectory());
    slugs.push(...files.map(f => f.replace('.json', '')));
  } catch {}

  return [...new Set(slugs)];
}
