// Golf Courses in Costa Blanca, Murcia & Almería
// ONLY courses with actual properties in our feed
// Used for golf pages, property filtering, and SEO

export interface GolfCourse {
  id: string;
  name: string;
  slug: string;
  shortName: string;
  region: 'south' | 'north' | 'murcia' | 'almeria';
  regionDisplay: string;
  town: string;
  lat: number;
  lng: number;
  holes: number;
  par?: number;
  designer?: string;
  yearOpened?: number;
  website?: string;
  description: string;
  story: string; // Engaging narrative about the course
  features: string[];
  highlights: string[]; // Short bullet points
  nearbyTowns: string[]; // Towns to filter properties by
  image?: string;
  // Extended info
  hotel?: string;
  amenities?: string[];
  greenFees?: string;
  courseLength?: string;
  priceFrom: number;
  propertyCount: number;
  tier: 'premium' | 'popular' | 'value' | 'growing' | 'lifestyle' | 'unique';
  gradient: string; // For visual styling
  builders?: { name: string; slug: string }[];
  relatedDevelopments?: { name: string; slug: string }[];
}

export const GOLF_COURSES: GolfCourse[] = [
  // ============================================
  // COSTA CÁLIDA (MURCIA) - Best Value Region
  // ============================================
  {
    id: 'serena-golf',
    name: 'Serena Golf',
    shortName: 'Serena Golf',
    slug: 'serena-golf',
    region: 'murcia',
    regionDisplay: 'Costa Cálida (Murcia)',
    town: 'Los Alcázares',
    lat: 37.7456,
    lng: -0.8456,
    holes: 18,
    par: 71,
    designer: 'Dave Thomas',
    yearOpened: 2007,
    description: 'Serena Golf is a modern links-style course near the Mar Menor, Spain\'s largest saltwater lagoon. The course features wide fairways, strategic bunkers, and stunning views towards the Mediterranean. Sea breezes add challenge to what is otherwise an accessible layout for golfers of all levels.',
    story: 'Serena Golf has become a hotspot for new build developments with multiple quality builders creating modern apartments and villas. The combination of links-style golf, Mar Menor beaches just minutes away, and competitive property prices makes this one of the most attractive golf destinations in Spain.',
    features: [
      '18-hole links-style course',
      'Par 71 / 6,200 meters',
      'Mar Menor & sea views',
      'Modern practice facilities',
      'Clubhouse restaurant & bar',
      'Pro shop with equipment rental',
      'Electric buggy hire',
      'Golf academy for all levels'
    ],
    highlights: ['Mar Menor views', 'Links-style', 'New developments', 'Beach access'],
    nearbyTowns: ['Los Alcázares', 'Torre Pacheco', 'San Javier', 'Santiago de la Ribera', 'Roda'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Practice facilities', 'Swimming pool'],
    priceFrom: 180000,
    propertyCount: 34,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=80',
    tier: 'popular',
    builders: [
      { name: 'Grupo Vermell', slug: 'grupo-vermell' },
      { name: 'AMAL', slug: 'amal' }
    ],
  },
  {
    id: 'hacienda-del-alamo',
    name: 'Hacienda del Álamo Golf Resort',
    shortName: 'Hacienda del Álamo',
    slug: 'hacienda-del-alamo',
    region: 'murcia',
    regionDisplay: 'Costa Cálida (Murcia)',
    town: 'Fuente Álamo',
    lat: 37.7234,
    lng: -1.1345,
    holes: 18,
    par: 72,
    designer: 'Dave Thomas',
    yearOpened: 2005,
    description: 'Hacienda del Álamo is an expansive resort in the Murcia countryside with a challenging desert-style championship course. Wide open spaces, strategic water features, and mountain backdrops create a unique golfing experience that differs from coastal courses.',
    story: 'Hacienda del Álamo offers some of the best value in the region. The resort combines quality golf with spacious living - villas here have generous plots and the resort has excellent facilities including pools, spa, and tennis courts. Popular with families seeking space and sunshine.',
    features: [
      '18-hole championship course',
      'Par 72 / 6,400 meters',
      'Desert-style layout',
      'Mountain backdrop views',
      'Full practice facilities',
      'Clubhouse & restaurant',
      'On-site spa & wellness',
      'Multiple swimming pools'
    ],
    highlights: ['Desert-style course', 'Spacious resort', 'Great value', 'Mountain views'],
    nearbyTowns: ['Fuente Álamo', 'Mazarrón', 'Cartagena', 'Torre Pacheco'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Pool', 'Spa', 'Tennis', 'Gym'],
    priceFrom: 175000,
    propertyCount: 9,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80',
    tier: 'value',
  },
  {
    id: 'peraleja-golf',
    name: 'Peraleja Golf Resort',
    shortName: 'Peraleja',
    slug: 'peraleja-golf',
    region: 'murcia',
    regionDisplay: 'Costa Cálida (Murcia)',
    town: 'Sucina',
    lat: 37.8123,
    lng: -0.9567,
    holes: 18,
    par: 72,
    designer: 'European Golf Design',
    yearOpened: 2008,
    description: 'Peraleja Golf Resort is a modern championship course with excellent facilities and a growing residential community. The well-maintained fairways and challenging greens suit all levels of golfer.',
    story: 'Peraleja is developing rapidly with new phases of villas and apartments. The Peralia Origenes development offers modern designs with golf views. Close proximity to both Mar Menor beaches and Murcia city makes this an excellent choice for those wanting the best of both worlds.',
    features: [
      '18-hole championship course',
      'Par 72 layout',
      'Modern course design',
      'Excellent practice facilities',
      'Clubhouse with restaurant',
      'Swimming pool complex',
      'Growing community',
      'Family-friendly atmosphere'
    ],
    highlights: ['Modern resort', 'Growing community', 'Good facilities', 'Family-friendly'],
    nearbyTowns: ['Sucina', 'Los Alcázares', 'Torre Pacheco', 'Roda', 'San Javier'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Pool', 'Practice area'],
    priceFrom: 170000,
    propertyCount: 7,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?w=800&q=80',
    tier: 'growing',
  },
  {
    id: 'altorreal-golf',
    name: 'Altorreal Golf Club',
    shortName: 'Altorreal',
    slug: 'altorreal-golf',
    region: 'murcia',
    regionDisplay: 'Murcia Inland',
    town: 'Molina de Segura',
    lat: 38.0712,
    lng: -1.1234,
    holes: 18,
    par: 72,
    designer: 'Dave Thomas',
    yearOpened: 1995,
    description: 'Altorreal Golf Club is an established parkland course in the Murcia hills with mature trees and excellent conditioning. This is a more traditional layout that rewards accurate play and course management.',
    story: 'Taylor Wimpey España is building the luxury Allure development here - high-spec villas in a prestigious, mature setting. Altorreal attracts a more discerning buyer looking for established gardens, privacy, and a quality course on their doorstep.',
    features: [
      '18-hole parkland course',
      'Par 72 / mature layout',
      'Established trees & landscaping',
      'Championship conditioning',
      'Traditional clubhouse',
      'Tennis & paddle courts',
      'Prestigious setting',
      'Quiet residential area'
    ],
    highlights: ['Established course', 'Mature trees', 'Prestigious area', 'Taylor Wimpey'],
    nearbyTowns: ['Molina de Segura', 'Murcia City', 'Alcantarilla'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Tennis', 'Paddle'],
    priceFrom: 350000,
    propertyCount: 4,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1624722610740-71fa0eb2cd5b?w=800&q=80',
    tier: 'premium',
    builders: [
      { name: 'Taylor Wimpey España', slug: 'taylor-wimpey' }
    ],
  },
  {
    id: 'roda-golf',
    name: 'Roda Golf & Beach Resort',
    shortName: 'Roda Golf',
    slug: 'roda-golf',
    region: 'murcia',
    regionDisplay: 'Costa Cálida (Murcia)',
    town: 'San Javier',
    lat: 37.7845,
    lng: -0.8012,
    holes: 18,
    par: 72,
    designer: 'Dave Thomas',
    yearOpened: 2006,
    description: 'Roda Golf & Beach Resort combines the best of both worlds - a quality championship course and proximity to Mar Menor beaches. The well-designed layout features water hazards and Mediterranean views.',
    story: 'Roda Golf perfectly combines beach and golf lifestyle. Just minutes from the warm waters of the Mar Menor and the beaches of San Javier, this resort offers modern residences with easy access to both course and coast. Popular with families and those seeking an active lifestyle.',
    features: [
      '18-hole championship course',
      'Par 72 layout',
      'Water features throughout',
      'Mediterranean views',
      'Beach proximity',
      'Modern clubhouse',
      'Beach club access',
      'Family facilities'
    ],
    highlights: ['Beach proximity', 'Mar Menor location', 'Resort lifestyle', 'Water features'],
    nearbyTowns: ['San Javier', 'Santiago de la Ribera', 'Los Alcázares', 'Roda', 'Torre Pacheco'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Beach club', 'Pool'],
    priceFrom: 195000,
    propertyCount: 3,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1624722610740-71fa0eb2cd5b?w=800&q=80',
    tier: 'lifestyle',
  },

  // ============================================
  // COSTA BLANCA SOUTH
  // ============================================
  {
    id: 'la-finca-golf',
    name: 'La Finca Golf Resort',
    shortName: 'La Finca',
    slug: 'la-finca-golf',
    region: 'south',
    regionDisplay: 'Costa Blanca South',
    town: 'Algorfa',
    lat: 38.0647,
    lng: -0.7928,
    holes: 18,
    par: 72,
    designer: 'Pepe Gancedo',
    yearOpened: 2002,
    website: 'https://www.lafincagolf.com',
    description: 'La Finca Golf Resort is one of Costa Blanca South\'s premier golf destinations. This challenging 18-hole, par 72 championship course winds through stunning Mediterranean landscapes with strategic water hazards and well-protected greens.',
    story: 'La Finca offers exceptional value with modern villas from multiple builders. The resort has a 4-star hotel, spa, and excellent facilities. Popular with buyers seeking the golf lifestyle without the coastal price premium - you can be on the beach in 15 minutes.',
    features: [
      '18-hole championship course',
      'Par 72 / 6,016 meters',
      'Pepe Gancedo design',
      'Driving range & practice facilities',
      'Professional golf academy',
      'Clubhouse with panoramic restaurant',
      'Fully stocked pro shop',
      '4-star resort hotel on-site'
    ],
    highlights: ['Mountain views', 'Great value', 'Multiple builders', 'Quality course'],
    nearbyTowns: ['Algorfa', 'La Finca', 'Quesada', 'Ciudad Quesada', 'Rojales', 'Guardamar'],
    hotel: 'La Finca Golf & Spa Hotel (4-star)',
    amenities: ['4-star hotel', 'Spa & wellness', 'Swimming pools', 'Tennis courts', 'Paddle tennis', 'Gym', 'Multiple restaurants'],
    greenFees: 'From €50 (residents) / €75 (visitors)',
    courseLength: '6,016m (white tees)',
    priceFrom: 150000,
    propertyCount: 14,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80',
    tier: 'value',
    builders: [
      { name: 'Contrimar', slug: 'contrimar' }
    ],
    relatedDevelopments: [
      { name: 'Oasis Villas 2 La Finca', slug: 'oasis-villas-2-la-finca' }
    ],
  },
  {
    id: 'vistabella-golf',
    name: 'Vistabella Golf',
    shortName: 'Vistabella',
    slug: 'vistabella-golf',
    region: 'south',
    regionDisplay: 'Costa Blanca South',
    town: 'Orihuela',
    lat: 38.0234,
    lng: -0.7856,
    holes: 18,
    par: 72,
    designer: 'Manuel Piñero',
    yearOpened: 2007,
    description: 'Vistabella Golf is a championship course designed by Ryder Cup legend Manuel Piñero. A challenging but fair course with excellent conditioning and mountain views that rewards accurate shot-making.',
    story: 'Vistabella is a growing resort with new developments from quality builders. The course design by Ryder Cup captain Manuel Piñero ensures quality, while the inland location means better value than coastal resorts. New phases continue to be released.',
    features: [
      '18-hole championship course',
      'Par 72 layout',
      'Manuel Piñero design',
      'Mountain backdrop',
      'Excellent conditioning',
      'Modern clubhouse',
      'Swimming pool',
      'Practice facilities'
    ],
    highlights: ['Piñero design', 'Growing resort', 'New developments', 'Mountain setting'],
    nearbyTowns: ['Vistabella', 'Quesada', 'Rojales', 'Algorfa', 'San Miguel de Salinas', 'Orihuela'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Pool', 'Practice facilities'],
    priceFrom: 180000,
    propertyCount: 9,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=80',
    tier: 'growing',
  },
  {
    id: 'lo-romero-golf',
    name: 'Lo Romero Golf',
    shortName: 'Lo Romero',
    slug: 'lo-romero-golf',
    region: 'south',
    regionDisplay: 'Costa Blanca South',
    town: 'Pilar de la Horadada',
    lat: 37.8456,
    lng: -0.7812,
    holes: 18,
    par: 72,
    designer: 'David Thomas',
    yearOpened: 2008,
    description: 'Lo Romero Golf is a modern championship course near the Mar Menor. Wide fairways and strategic bunkering make it enjoyable for all levels while still offering challenge for low handicappers.',
    story: 'Lo Romero is developing with new build options in a great location. Close to both Costa Blanca beaches and Mar Menor, it offers good connectivity and a modern golfing experience. The course is well-maintained and less crowded than coastal courses.',
    features: [
      '18-hole championship course',
      'Par 72 layout',
      'Modern course design',
      'Wide fairways',
      'Strategic bunkering',
      'Good practice facilities',
      'Swimming pool',
      'Near Mar Menor'
    ],
    highlights: ['Modern course', 'Near Mar Menor', 'Good facilities', 'New developments'],
    nearbyTowns: ['Pilar de la Horadada', 'San Pedro del Pinatar', 'Torre de la Horadada', 'Lo Pagan'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Pool', 'Practice area'],
    priceFrom: 185000,
    propertyCount: 2,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80',
    tier: 'value',
  },
  {
    id: 'la-marquesa-golf',
    name: 'Golf La Marquesa',
    shortName: 'La Marquesa',
    slug: 'la-marquesa-golf',
    region: 'south',
    regionDisplay: 'Costa Blanca South',
    town: 'Rojales',
    lat: 38.0512,
    lng: -0.7823,
    holes: 18,
    par: 72,
    designer: 'Juanjo Losáñez',
    yearOpened: 1989,
    description: 'Golf La Marquesa is an established course in the heart of the Vega Baja region. Tree-lined fairways and water features create an attractive parkland layout that has matured beautifully over the years.',
    story: 'La Marquesa offers affordable golf resort living with the Terrazas Golf development providing modern apartments overlooking the course. An established community with a friendly atmosphere and one of the most accessible golf lifestyles in the region.',
    features: [
      '18-hole parkland course',
      'Par 72 layout',
      'Established tree-lined fairways',
      'Water features',
      'Central Vega Baja location',
      'Traditional clubhouse',
      'Friendly atmosphere',
      'Affordable green fees'
    ],
    highlights: ['Established course', 'Affordable options', 'Central location', 'Parkland style'],
    nearbyTowns: ['Rojales', 'Quesada', 'Ciudad Quesada', 'Guardamar', 'Algorfa'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Practice area'],
    priceFrom: 165000,
    propertyCount: 1,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?w=800&q=80',
    tier: 'value',
  },

  {
    id: 'villamartin-golf',
    name: 'Villamartin Golf',
    shortName: 'Villamartin',
    slug: 'villamartin-golf',
    region: 'south',
    regionDisplay: 'Costa Blanca South',
    town: 'Orihuela Costa',
    lat: 37.9340,
    lng: -0.7350,
    holes: 18,
    par: 72,
    designer: 'Robert Dean Putman',
    yearOpened: 1972,
    website: 'https://www.villamartingolf.com',
    description: 'Villamartin is one of the Costa Blanca\'s most iconic and established golf courses. This mature 18-hole championship course in the heart of Orihuela Costa features tree-lined fairways, strategic water hazards, and immaculate conditioning. Home to many major amateur tournaments, it is the social hub of the region\'s golf community.',
    story: 'Villamartin is where golf culture began on the southern Costa Blanca. The Villamartin Plaza — just steps from the course — is the legendary meeting point for thousands of expats, with restaurants, bars, and a social calendar that runs year-round. Properties around Villamartin range from affordable apartments to luxury villas, with one of the largest and most established expat communities in Spain. For buyers who want to live at the center of golf social life, Villamartin is the original and the best.',
    features: [
      '18-hole championship course',
      'Par 72 / 6,132 meters',
      'Established 1972 — iconic status',
      'Mature tree-lined fairways',
      'Tournament-standard conditioning',
      'Famous Villamartin Plaza social hub',
      'Full practice facilities & academy',
      'Clubhouse restaurant & pro shop'
    ],
    highlights: ['Iconic since 1972', 'Villamartin Plaza social hub', 'Largest expat community', 'Tournament hosting'],
    nearbyTowns: ['Orihuela Costa', 'Villamartin', 'La Zenia', 'Playa Flamenca', 'Cabo Roig', 'Punta Prima', 'Torrevieja'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Practice facilities', 'Academy', 'Tennis'],
    greenFees: 'From €40 (twilight) / €70 (peak)',
    courseLength: '6,132m',
    priceFrom: 120000,
    propertyCount: 5,
    gradient: 'from-primary-900 to-primary-800',
    image: '/images/Drone 2/Golf/Villa Martin Golf.jpg',
    tier: 'popular',
  },
  {
    id: 'las-ramblas-golf',
    name: 'Las Ramblas Golf',
    shortName: 'Las Ramblas',
    slug: 'las-ramblas-golf',
    region: 'south',
    regionDisplay: 'Costa Blanca South',
    town: 'Orihuela Costa',
    lat: 37.9270,
    lng: -0.7420,
    holes: 18,
    par: 72,
    designer: 'Stirling & Martin',
    yearOpened: 1991,
    description: 'Las Ramblas is a technical 18-hole course set in a natural ravine landscape adjacent to Villamartin. The undulating terrain creates dramatic elevation changes, blind shots, and scenic views that make every round memorable. Considered one of the most visually striking courses on the southern Costa Blanca.',
    story: 'Las Ramblas sits within the "Golden Triangle" of Orihuela Costa golf — alongside Villamartin and Campoamor. The three courses share the area between La Zenia Boulevard (the largest shopping center in Alicante province) and some of the Costa Blanca\'s best beaches. Properties near Las Ramblas benefit from this concentration of amenities, with the added attraction of a quieter, more natural setting than neighboring Villamartin.',
    features: [
      '18-hole course with elevation changes',
      'Par 72 / ravine landscape',
      'Dramatic natural terrain',
      'Adjacent to Villamartin & Campoamor',
      'Near La Zenia Boulevard shopping',
      'Modern clubhouse & restaurant',
      'Practice facilities',
      'Equipment rental'
    ],
    highlights: ['Golden Triangle location', 'Dramatic ravine terrain', 'Near La Zenia Boulevard', 'Visual stunner'],
    nearbyTowns: ['Orihuela Costa', 'La Zenia', 'Playa Flamenca', 'Villamartin', 'Cabo Roig', 'Torrevieja'],
    amenities: ['Clubhouse', 'Restaurant', 'Pro shop', 'Practice area'],
    greenFees: 'From €35 (twilight) / €60 (peak)',
    priceFrom: 120000,
    propertyCount: 3,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1624722610740-71fa0eb2cd5b?w=800&q=80',
    tier: 'popular',
  },
  {
    id: 'campoamor-golf',
    name: 'Real Club de Golf Campoamor',
    shortName: 'Campoamor',
    slug: 'campoamor-golf',
    region: 'south',
    regionDisplay: 'Costa Blanca South',
    town: 'Orihuela Costa',
    lat: 37.8890,
    lng: -0.7480,
    holes: 18,
    par: 72,
    designer: 'Juanjo Losáñez',
    yearOpened: 1989,
    description: 'Real Club de Golf Campoamor is the southernmost course of Orihuela Costa\'s famed Golden Triangle. This flat, parkland-style course features wide fairways, palm-lined avenues, and water features. Its accessible layout and gentle terrain make it popular with golfers of all levels.',
    story: 'Campoamor completes the trio with Villamartin and Las Ramblas, giving Orihuela Costa the highest concentration of quality golf courses on the southern Costa Blanca. The Dehesa de Campoamor area is one of the most upmarket residential zones in the region, known for prestigious developments, beach proximity (Playa de Campoamor), and a refined atmosphere. Properties range from modern apartments to exclusive seafront villas.',
    features: [
      '18-hole parkland course',
      'Par 72 / accessible layout',
      'Palm-lined fairways',
      'Water features throughout',
      'Gentle, walkable terrain',
      'Clubhouse with panoramic terrace',
      'Pro shop & practice facilities',
      'Close to Campoamor beach'
    ],
    highlights: ['Golden Triangle third', 'Flat walkable course', 'Upmarket Campoamor area', 'Near beach'],
    nearbyTowns: ['Orihuela Costa', 'Campoamor', 'Cabo Roig', 'Pilar de la Horadada', 'Playa Flamenca', 'Mil Palmeras'],
    amenities: ['Clubhouse', 'Restaurant', 'Pro shop', 'Practice area', 'Pool'],
    greenFees: 'From €35 (twilight) / €65 (peak)',
    priceFrom: 140000,
    propertyCount: 4,
    gradient: 'from-primary-900 to-primary-800',
    image: '/images/Drone 2/Golf/Campoamor Golf (1).jpg',
    tier: 'popular',
  },
  {
    id: 'las-colinas-golf',
    name: 'Las Colinas Golf & Country Club',
    shortName: 'Las Colinas',
    slug: 'las-colinas-golf',
    region: 'south',
    regionDisplay: 'Costa Blanca South',
    town: 'San Miguel de Salinas',
    lat: 37.9123,
    lng: -0.7690,
    holes: 18,
    par: 71,
    designer: 'Cabell B. Robinson',
    yearOpened: 2010,
    website: 'https://www.lascolinasgolf.es',
    description: 'Las Colinas Golf & Country Club is the most prestigious golf resort on the southern Costa Blanca. The Cabell B. Robinson-designed championship course has been rated among Spain\'s top 10 courses, featuring dramatic natural terrain, lake holes, and impeccable conditioning. The resort has won multiple "Best Golf Resort in Spain" awards.',
    story: 'Las Colinas is the jewel in the crown of Costa Blanca South golf. This award-winning resort attracts serious golfers and premium property buyers from across Europe. The exclusive residential community features luxury villas and contemporary apartments, all built to exceptional standards within a gated, security-patrolled environment. Beach Club membership at nearby Campoamor beach, fine dining restaurants, and a wellness center complete the premium lifestyle. For buyers seeking the absolute best in golf resort living, Las Colinas is in a class of its own.',
    features: [
      '18-hole championship course — Top 10 in Spain',
      'Par 71 / Cabell B. Robinson design',
      'Multi-award winning resort',
      'Dramatic natural landscape with lakes',
      'Exclusive gated residential community',
      'Beach Club at Campoamor beach',
      'Fine dining & wellness center',
      'Security-patrolled estate'
    ],
    highlights: ['Top 10 in Spain', 'Award-winning resort', 'Exclusive gated community', 'Beach Club'],
    nearbyTowns: ['San Miguel de Salinas', 'Campoamor', 'Orihuela Costa', 'Pilar de la Horadada', 'Torrevieja'],
    hotel: 'On-site luxury residences & Beach Club',
    amenities: ['Clubhouse', 'Fine dining', 'Spa & wellness', 'Beach Club', 'Pool', 'Tennis', 'Gym', 'Pro shop'],
    greenFees: 'From €65 (residents) / €110 (visitors)',
    courseLength: '6,264m',
    priceFrom: 350000,
    propertyCount: 5,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?w=800&q=80',
    tier: 'premium',
  },

  // ============================================
  // COSTA BLANCA NORTH
  // ============================================
  {
    id: 'la-sella-golf',
    name: 'La Sella Golf Resort & Spa',
    shortName: 'La Sella',
    slug: 'la-sella-golf',
    region: 'north',
    regionDisplay: 'Costa Blanca North',
    town: 'Denia',
    lat: 38.7870,
    lng: -0.0250,
    holes: 27,
    par: 72,
    designer: 'José María Olazábal',
    yearOpened: 1991,
    website: 'https://www.lasellagolf.com',
    description: 'La Sella Golf Resort is one of the Costa Blanca\'s most prestigious golf destinations, featuring 27 holes across three 9-hole courses designed by Major winner José María Olazábal. Set against the dramatic backdrop of the Montgó mountain near Dénia, the resort combines championship golf with a 5-star Marriott hotel and spa.',
    story: 'La Sella represents the pinnacle of golf living on the northern Costa Blanca. The three courses — Mestral, Llebeig, and Gregal — each offer a distinct character, from technical woodland to open parkland. With the Denia Marriott resort on-site and the charming old town of Dénia just 10 minutes away, this is where golf lifestyle meets Mediterranean culture at its finest. Properties near La Sella range from hillside villas with golf views to modern apartments in the surrounding villages of Pedreguer and Jesús Pobre.',
    features: [
      '27 holes across three 9-hole courses',
      'José María Olazábal design',
      'Mestral, Llebeig & Gregal courses',
      'Denia Marriott La Sella Golf Resort & Spa',
      'Dramatic Montgó mountain backdrop',
      'Full practice facilities & golf academy',
      'Pro shop & clubhouse restaurant',
      'Swimming pool & tennis courts'
    ],
    highlights: ['Olazábal design', '27 holes', 'Marriott 5-star', 'Montgó mountain views'],
    nearbyTowns: ['Denia', 'Pedreguer', 'Jesús Pobre', 'Jávea', 'Ondara', 'Gata de Gorgos'],
    hotel: 'Denia Marriott La Sella Golf Resort & Spa (5-star)',
    amenities: ['Marriott Hotel', 'Spa & wellness', 'Swimming pools', 'Tennis', 'Restaurant', 'Pro shop', 'Golf academy'],
    greenFees: 'From €55 (residents) / €85 (visitors)',
    courseLength: '3,100m per 9-hole loop',
    priceFrom: 250000,
    propertyCount: 3,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=80',
    tier: 'premium',
  },
  {
    id: 'bonalba-golf',
    name: 'Bonalba Golf',
    shortName: 'Bonalba',
    slug: 'bonalba-golf',
    region: 'north',
    regionDisplay: 'Costa Blanca North',
    town: 'Mutxamel',
    lat: 38.4260,
    lng: -0.4270,
    holes: 18,
    par: 72,
    designer: 'Ramón Espinosa',
    yearOpened: 1994,
    website: 'https://www.bonalbagolf.com',
    description: 'Bonalba Golf is a well-established championship course just 10 minutes from Alicante city and 5 minutes from the airport. The 18-hole layout winds through Mediterranean pines and almond groves with views to the mountains, offering a challenging but enjoyable round in a convenient location.',
    story: 'Bonalba is the most accessible quality golf course to Alicante airport, making it hugely popular with visiting golfers and those relocating to the area. The Hotel Bonalba resort provides accommodation and spa facilities, while the surrounding Mutxamel area offers excellent value property compared to the coast. Buyers here get genuine Spanish town living with championship golf on their doorstep and Alicante\'s beaches 15 minutes away.',
    features: [
      '18-hole championship course',
      'Par 72 / 6,100 meters',
      'Mediterranean pine & almond groves',
      'Mountain backdrop views',
      'Hotel Bonalba on-site',
      'Driving range & practice area',
      'Clubhouse restaurant & terrace',
      'Swimming pool & spa facilities'
    ],
    highlights: ['Closest to Alicante airport', '18 championship holes', 'Hotel on-site', 'Mountain setting'],
    nearbyTowns: ['Mutxamel', 'Alicante', 'San Juan', 'Campello', 'San Vicente del Raspeig', 'Jijona'],
    hotel: 'Hotel Bonalba Alicante (4-star)',
    amenities: ['Hotel', 'Spa', 'Swimming pool', 'Restaurant', 'Pro shop', 'Practice facilities'],
    greenFees: 'From €40 (twilight) / €65 (peak)',
    courseLength: '6,100m',
    priceFrom: 200000,
    propertyCount: 2,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80',
    tier: 'value',
  },
  {
    id: 'javea-golf',
    name: 'Club de Golf Jávea',
    shortName: 'Jávea Golf',
    slug: 'javea-golf',
    region: 'north',
    regionDisplay: 'Costa Blanca North',
    town: 'Jávea',
    lat: 38.7650,
    lng: -0.1150,
    holes: 9,
    par: 36,
    yearOpened: 1981,
    website: 'https://www.clubdegolfjavea.com',
    description: 'Club de Golf Jávea is a charming 9-hole course nestled between the Montgó mountain and the sea in one of the Costa Blanca\'s most prestigious towns. The compact layout delivers character and challenge in equal measure, with mature trees and mountain views from every hole.',
    story: 'Jávea Golf may be small but its location is unbeatable. This is one of the most desirable addresses on the entire Costa Blanca — Jávea attracts discerning international buyers who value old-town charm, dramatic coastline, and a refined lifestyle. Properties near the golf course range from luxury villas on the slopes of Montgó to elegant townhouses in the nearby Benitachell and Cumbre del Sol areas. For buyers who want golf, beach, and culture in one package, Jávea delivers.',
    features: [
      '9-hole course, par 36',
      'Scenic Montgó mountain setting',
      'Mature Mediterranean landscaping',
      'Clubhouse with restaurant',
      'Practice putting green',
      'Equipment hire available',
      'Walking distance to town',
      'Family-friendly atmosphere'
    ],
    highlights: ['Premium Jávea location', 'Montgó mountain setting', 'Prestigious address', 'Walkable town'],
    nearbyTowns: ['Jávea', 'Benitachell', 'Moraira', 'Denia', 'Teulada', 'Gata de Gorgos'],
    amenities: ['Clubhouse', 'Restaurant', 'Practice area', 'Equipment hire'],
    greenFees: 'From €35 (9 holes) / €55 (18 holes with replay)',
    priceFrom: 300000,
    propertyCount: 3,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1624722610740-71fa0eb2cd5b?w=800&q=80',
    tier: 'premium',
  },
  {
    id: 'ifach-golf',
    name: 'Club de Golf Ifach',
    shortName: 'Ifach Golf',
    slug: 'ifach-golf',
    region: 'north',
    regionDisplay: 'Costa Blanca North',
    town: 'Benissa',
    lat: 38.7000,
    lng: -0.0550,
    holes: 9,
    par: 34,
    yearOpened: 1974,
    description: 'Club de Golf Ifach is one of the oldest golf clubs on the Costa Blanca, established in 1974 in the hills between Calpe and Benissa. This intimate 9-hole course offers spectacular views of the iconic Peñón de Ifach rock and the Mediterranean, with a laid-back atmosphere that feels like a private members\' retreat.',
    story: 'Ifach Golf sits in the heart of one of the Costa Blanca\'s most sought-after residential zones. The Benissa-Calpe corridor is home to some of the finest villas on the coast, with properties commanding sea views toward the dramatic Peñón de Ifach. This established course attracts a loyal international community — many of whom live within walking distance. For buyers seeking a quiet, premium lifestyle with golf, stunning coastal scenery, and proximity to the charming towns of Calpe, Benissa, and Moraira, the Ifach area is a hidden gem.',
    features: [
      '9-hole course, par 34',
      'Established 1974 — oldest in the area',
      'Spectacular Peñón de Ifach views',
      'Hilltop Mediterranean setting',
      'Intimate club atmosphere',
      'Clubhouse café & terrace',
      'Equipment rental available',
      'Swimming pool'
    ],
    highlights: ['Peñón de Ifach views', 'Established 1974', 'Premium Calpe-Benissa area', 'Sea views'],
    nearbyTowns: ['Benissa', 'Calpe', 'Moraira', 'Teulada', 'Altea', 'Jávea'],
    amenities: ['Clubhouse', 'Café & terrace', 'Pool', 'Equipment hire'],
    greenFees: 'From €30 (9 holes) / €50 (18 holes)',
    priceFrom: 280000,
    propertyCount: 2,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80',
    tier: 'premium',
  },
  {
    id: 'bernia-golf',
    name: 'Don Cayo Golf (Bernia Golf)',
    shortName: 'Bernia Golf',
    slug: 'bernia-golf',
    region: 'north',
    regionDisplay: 'Costa Blanca North',
    town: 'Altea',
    lat: 38.6320,
    lng: -0.0400,
    holes: 9,
    par: 33,
    description: 'Don Cayo Golf — commonly known as Bernia Golf — is a scenic 9-hole course perched in the hills above Altea with panoramic views of the Mediterranean and Sierra de Bernia mountains. The elevated position and mountain-to-sea views make every round a visual feast.',
    story: 'Bernia Golf is the social heart of the Altea Hills and Sierra Altea residential areas, where an established international community enjoys one of the most beautiful settings on the Costa Blanca. The course sits among premium villa developments like Sierra Altea and the wider Altea Hills urbanization, where properties with golf and sea views command strong prices. Altea itself — with its blue-domed church, artist quarter, and seafront promenade — is consistently voted one of the prettiest towns in Spain.',
    features: [
      '9-hole hilltop course, par 33',
      'Panoramic Mediterranean sea views',
      'Sierra de Bernia mountain backdrop',
      'Elevated hillside position',
      'Restaurant with terrace views',
      'Relaxed social atmosphere',
      'Practice area',
      'Equipment rental'
    ],
    highlights: ['Stunning hilltop views', 'Sierra de Bernia setting', 'Altea\'s prettiest location', 'Social club'],
    nearbyTowns: ['Altea', 'Altea Hills', 'Alfaz del Pi', 'Benidorm', 'Calpe', 'La Nucia'],
    amenities: ['Restaurant', 'Terrace', 'Practice area', 'Equipment hire'],
    greenFees: 'From €25 (9 holes) / €40 (18 holes)',
    priceFrom: 250000,
    propertyCount: 2,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?w=800&q=80',
    tier: 'lifestyle',
  },
  {
    id: 'alicante-golf',
    name: 'Alicante Golf',
    shortName: 'Alicante Golf',
    slug: 'alicante-golf',
    region: 'north',
    regionDisplay: 'Costa Blanca North',
    town: 'Alicante',
    lat: 38.3730,
    lng: -0.4320,
    holes: 18,
    par: 72,
    designer: 'Severiano Ballesteros',
    yearOpened: 1998,
    website: 'https://www.alicantegolf.com',
    description: 'Alicante Golf is a championship 18-hole course designed by the legendary Severiano Ballesteros, located in the Playa de San Juan area of Alicante city. The course offers a challenging parkland layout with water features and is one of the best urban golf courses in Spain.',
    story: 'Alicante Golf delivers something rare — a Ballesteros-designed championship course within a major city. Located next to San Juan beach and the Alicante tram line, it is perfect for buyers who want urban convenience with golf on their doorstep. The surrounding Playa de San Juan and Albufereta neighborhoods offer beachfront apartments and modern developments, while the course itself is framed by the Hotel Alicante Golf. For buyers who want city life, beach access, and quality golf without driving, Alicante Golf is the answer.',
    features: [
      '18-hole championship course',
      'Par 72 / Severiano Ballesteros design',
      'Urban location near Playa de San Juan',
      'Water features & strategic bunkering',
      'Hotel Alicante Golf on-site',
      'Full practice facilities & academy',
      'Clubhouse restaurant & pro shop',
      'Tram connection to Alicante center'
    ],
    highlights: ['Ballesteros design', 'City & beach location', 'Hotel on-site', 'Tram connected'],
    nearbyTowns: ['Alicante', 'San Juan', 'Campello', 'Mutxamel', 'Playa de San Juan'],
    hotel: 'Hotel Alicante Golf (4-star)',
    amenities: ['Hotel', 'Restaurant', 'Pro shop', 'Practice facilities', 'Academy', 'Pool'],
    greenFees: 'From €45 (twilight) / €75 (peak)',
    courseLength: '6,200m',
    priceFrom: 220000,
    propertyCount: 3,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=80',
    tier: 'lifestyle',
  },
  {
    id: 'puig-campana-golf',
    name: 'Villaitana Golf (Puig Campana)',
    shortName: 'Villaitana',
    slug: 'puig-campana-golf',
    region: 'north',
    regionDisplay: 'Costa Blanca North',
    town: 'Finestrat',
    lat: 38.5523,
    lng: -0.0934,
    holes: 36,
    par: 72,
    designer: 'Jack Nicklaus & Severiano Ballesteros',
    yearOpened: 2009,
    website: 'https://www.villaitana.com',
    description: 'Villaitana offers two championship courses designed by golfing legends. The Levante course by Jack Nicklaus is more challenging, while the Poniente course suits all levels. The dramatic Puig Campana mountain provides a stunning backdrop.',
    story: 'The only 36-hole resort in Costa Blanca offers luxury living in a stunning setting. Prime Home Alicante is developing here with the Green & Blue project - premium properties with access to world-class golf, a 5-star Meliá hotel, and proximity to Benidorm.',
    features: [
      '36 holes (two courses)',
      'Jack Nicklaus design (Levante)',
      'Severiano Ballesteros design (Poniente)',
      'Dramatic Puig Campana views',
      '5-star Meliá Villaitana hotel',
      'Full-service spa',
      'Multiple restaurants',
      'Premium practice facilities'
    ],
    highlights: ['36 holes', 'Nicklaus & Ballesteros', 'Mountain views', '5-star Meliá'],
    nearbyTowns: ['Finestrat', 'Benidorm', 'La Nucia', 'Alfaz del Pi', 'Altea'],
    hotel: 'Meliá Villaitana 5-star',
    amenities: ['Two clubhouses', 'Pro shop', 'Meliá Hotel', 'Spa', 'Restaurants', 'Pool', 'Tennis'],
    priceFrom: 350000,
    propertyCount: 3,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?w=800&q=80',
    tier: 'premium',
    builders: [
      { name: 'Prime Home Alicante', slug: 'prime-home-alicante' }
    ],
    relatedDevelopments: [
      { name: 'Green & Blue Villaitana', slug: 'green-blue-villaitana' }
    ],
  },

  // ============================================
  // ALMERÍA
  // ============================================
  {
    id: 'aguilon-golf',
    name: 'Aguilón Golf Resort',
    shortName: 'Aguilón',
    slug: 'aguilon-golf',
    region: 'almeria',
    regionDisplay: 'Almería',
    town: 'Pulpí',
    lat: 37.4012,
    lng: -1.6823,
    holes: 18,
    par: 72,
    designer: 'Manuel Piñero',
    yearOpened: 2009,
    description: 'Aguilón Golf Resort features a desert-links course designed by Ryder Cup captain Manuel Piñero. The dramatic landscape offers mountain and sea views from multiple holes, creating a unique golfing experience.',
    story: 'Aguilón offers a unique setting between mountains and sea in the unspoilt Almería province. New developments here provide excellent value with spectacular views. Lower profile than Costa Blanca but increasingly popular with those seeking authenticity and value.',
    features: [
      '18-hole desert-links course',
      'Par 72 / Manuel Piñero design',
      'Mountain & sea views',
      'Dramatic landscape',
      'Desert-style bunkers',
      'Modern clubhouse',
      'Great value green fees',
      'Uncrowded rounds'
    ],
    highlights: ['Piñero design', 'Sea & mountain views', 'Unique landscape', 'Great value'],
    nearbyTowns: ['Pulpí', 'San Juan de los Terreros', 'Vera', 'Águilas'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurant', 'Pool'],
    priceFrom: 200000,
    propertyCount: 4,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1624722610740-71fa0eb2cd5b?w=800&q=80',
    tier: 'value',
  },
  {
    id: 'desert-springs',
    name: 'Desert Springs Golf Club',
    shortName: 'Desert Springs',
    slug: 'desert-springs',
    region: 'almeria',
    regionDisplay: 'Almería',
    town: 'Cuevas del Almanzora',
    lat: 37.3156,
    lng: -1.7234,
    holes: 18,
    par: 72,
    designer: 'Indiana Golf Course Design',
    yearOpened: 2001,
    description: 'Desert Springs is an award-winning desert course unique in Europe. The Arizona-style layout features cacti, dry river beds, and stunning mountain scenery - a truly different golfing experience.',
    story: 'Desert Springs offers a truly unique Spanish golf experience - the only desert golf course in Europe. Attracts golfers seeking something different, with excellent year-round weather and a distinctive resort atmosphere. Properties here offer something genuinely different.',
    features: [
      '18-hole desert course',
      'Par 72 / unique in Europe',
      'Arizona-style landscape',
      'Cacti & desert flora',
      'Mountain scenery',
      'Award-winning design',
      'Year-round playability',
      'Full resort facilities'
    ],
    highlights: ['Unique desert style', 'Award-winning', 'Spectacular scenery', 'Year-round play'],
    nearbyTowns: ['Cuevas del Almanzora', 'Vera', 'Mojácar', 'Garrucha'],
    amenities: ['Clubhouse', 'Pro shop', 'Restaurants', 'Pool', 'Spa', 'Tennis'],
    priceFrom: 250000,
    propertyCount: 2,
    gradient: 'from-primary-900 to-primary-800',
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80',
    tier: 'unique',
  },
];

// Helper functions
export function getGolfCourseBySlug(slug: string): GolfCourse | undefined {
  return GOLF_COURSES.find(course => course.slug === slug);
}

export function getGolfCoursesByRegion(region: 'north' | 'south' | 'murcia' | 'almeria'): GolfCourse[] {
  return GOLF_COURSES.filter(course => course.region === region);
}

export function getGolfCoursesNearTown(town: string): GolfCourse[] {
  const townLower = town.toLowerCase();
  return GOLF_COURSES.filter(course =>
    course.nearbyTowns.some(t => t.toLowerCase() === townLower) ||
    course.town.toLowerCase() === townLower
  );
}

export function getAllGolfSlugs(): string[] {
  return GOLF_COURSES.map(course => course.slug);
}

// Get total property count across all courses
export function getTotalGolfProperties(): number {
  return GOLF_COURSES.reduce((sum, course) => sum + course.propertyCount, 0);
}

// Get courses sorted by property count
export function getCoursesByPropertyCount(): GolfCourse[] {
  return [...GOLF_COURSES].sort((a, b) => b.propertyCount - a.propertyCount);
}

// For Footer display - show courses with most properties
export const FOOTER_GOLF_COURSES = {
  south: GOLF_COURSES
    .filter(c => c.region === 'south')
    .sort((a, b) => b.propertyCount - a.propertyCount)
    .slice(0, 4)
    .map(c => ({ name: c.shortName, slug: c.slug })),
  murcia: GOLF_COURSES
    .filter(c => c.region === 'murcia')
    .sort((a, b) => b.propertyCount - a.propertyCount)
    .slice(0, 4)
    .map(c => ({ name: c.shortName, slug: c.slug })),
  other: GOLF_COURSES
    .filter(c => c.region === 'north' || c.region === 'almeria')
    .sort((a, b) => b.propertyCount - a.propertyCount)
    .slice(0, 4)
    .map(c => ({ name: c.shortName, slug: c.slug })),
};
