/**
 * AI-Generated Content Display Component
 * 
 * Renders the rich SEO content generated by AI
 * Falls back gracefully if content not available
 */

import { GeneratedContent } from '@/lib/ai-content-generator';

interface Props {
  content: GeneratedContent | null;
  developmentName: string;
}

export default function AIGeneratedContent({ content, developmentName }: Props) {
  if (!content) {
    return (
      <div className="prose prose-lg max-w-none">
        <p className="text-gray-600 italic">
          Detailed content for {developmentName} is being prepared. 
          Contact us for comprehensive information about this development.
        </p>
      </div>
    );
  }

  return (
    <div className="ai-generated-content">
      {/* Render the HTML content */}
      <article 
        className="prose prose-lg max-w-none
          prose-headings:text-deep-blue-800 
          prose-headings:font-semibold
          prose-h2:text-2xl prose-h2:mt-10 prose-h2:mb-4
          prose-h3:text-xl prose-h3:mt-6 prose-h3:mb-3
          prose-p:text-gray-700 prose-p:leading-relaxed
          prose-a:text-deep-blue-600 prose-a:font-medium prose-a:no-underline hover:prose-a:underline
          prose-ul:my-4 prose-li:my-1
          prose-table:my-6 prose-table:w-full
          prose-th:bg-gray-50 prose-th:p-3 prose-th:text-left prose-th:font-semibold
          prose-td:p-3 prose-td:border-b prose-td:border-gray-200"
        dangerouslySetInnerHTML={{ __html: content.html }}
      />
      
      {/* Generation timestamp (hidden, for reference) */}
      <div className="hidden">
        Content generated: {content.generatedAt.toISOString()}
      </div>
    </div>
  );
}

/**
 * FAQ Schema Component
 * 
 * Renders FAQ structured data for SEO
 */
export function FAQSchema({ faqs }: { faqs: GeneratedContent['faqs'] }) {
  if (!faqs || faqs.length === 0) return null;

  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqs.map(faq => ({
      "@type": "Question",
      "name": faq.question,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.answer
      }
    }))
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * Product Schema Component
 * 
 * Renders Product structured data for development
 */
export function DevelopmentSchema({ 
  development, 
  content 
}: { 
  development: {
    name: string;
    slug: string;
    developer: string;
    town: string;
    province: string;
    priceFrom: number | null;
    priceTo: number | null;
    bedroomRange: { min: number; max: number };
    types: string[];
  };
  content: GeneratedContent | null;
}) {
  const schema = {
    "@context": "https://schema.org/",
    "@type": "Product",
    "name": development.name,
    "description": content?.metaDescription || `New build ${development.types.join('/')} in ${development.town}`,
    "brand": {
      "@type": "Brand",
      "name": development.developer
    },
    "offers": development.priceFrom ? {
      "@type": "AggregateOffer",
      "url": `https://www.newbuildhomescostablanca.com/developments/${development.slug}/`,
      "priceCurrency": "EUR",
      "lowPrice": development.priceFrom,
      ...(development.priceTo && { "highPrice": development.priceTo }),
      "availability": "https://schema.org/InStock",
      "seller": {
        "@type": "RealEstateAgent",
        "name": "New Build Homes Costa Blanca"
      }
    } : undefined,
    "address": {
      "@type": "PostalAddress",
      "addressLocality": development.town,
      "addressRegion": development.province,
      "addressCountry": "ES"
    },
    "numberOfRooms": `${development.bedroomRange.min}-${development.bedroomRange.max}`
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * Breadcrumb Schema Component
 */
export function BreadcrumbSchema({ 
  items 
}: { 
  items: Array<{ name: string; url: string }>;
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": items.map((item, index) => ({
      "@type": "ListItem",
      "position": index + 1,
      "name": item.name,
      "item": item.url
    }))
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}
